import React, { useEffect, useState } from "react";
import { useWorkspace } from "./AppShell";

export default function GraphExplorer() {
  const {api,session,showError}=useWorkspace();
  const [devices,setDevices]=useState([]); const [selected,setSelected]=useState(""); const [graph,setGraph]=useState(null); const [detail,setDetail]=useState(null); const [loading,setLoading]=useState(false);
  useEffect(()=>{api.listDevices(session.userId).then((rows)=>{setDevices(rows); const initial=rows.find((d)=>d.asset_id==="CP4-001")?.asset_id||rows[0]?.asset_id; if(initial)setSelected(initial);}).catch((e)=>showError(e.reason));},[session.userId]);
  useEffect(()=>{if(!selected)return;setLoading(true);Promise.all([api.getDeviceGraph(selected,session.userId),api.getDevice(selected,session.userId)]).then(([g,d])=>{setGraph(g);setDetail(d);}).catch((e)=>showError(e.reason)).finally(()=>setLoading(false));},[selected,session.userId]);
  const center={x:330,y:210}; const related=(graph?.nodes||[]).filter((n)=>String(n.asset_id||n.id||n.name)!==selected); const pos=related.map((n,i)=>({node:n,x:330+Math.cos((i/Math.max(related.length,1))*Math.PI*2)*220,y:210+Math.sin((i/Math.max(related.length,1))*Math.PI*2)*145}));
  return <div className="graph-layout"><section className="panel graph-canvas"><div className="panel-heading"><div><span className="kicker">NEO4J NEIGHBORHOOD</span><h2>Connected asset graph</h2></div><label className="graph-select"><span>Selected device</span><select value={selected} onChange={(e)=>setSelected(e.target.value)}>{devices.map((d)=><option key={d.asset_id} value={d.asset_id}>{d.asset_id} · {d.device_name}</option>)}</select></label></div>{loading?<div className="graph-loading"><span className="spinner"/>Loading graph neighborhood…</div>:<svg viewBox="0 0 660 430" role="img" aria-label={`Direct graph neighborhood for ${selected}`}><g className="network-lines">{pos.map((p,i)=><line key={i} x1={center.x} y1={center.y} x2={p.x} y2={p.y}/>)}</g>{pos.map((p,i)=>{const label=p.node.asset_id||p.node.name||p.node.id||`Node ${i+1}`;return <g key={i} className="network-node"><circle cx={p.x} cy={p.y} r="40"/><text x={p.x} y={p.y+4}>{String(label).slice(0,14)}</text></g>})}<g className="network-node selected"><circle cx={center.x} cy={center.y} r="55"/><text x={center.x} y={center.y-3}>{selected}</text><text className="sub" x={center.x} y={center.y+17}>SELECTED</text></g></svg>}<div className="graph-legend"><span><i className="selected"/>Selected asset</span><span><i/>Direct relationship</span><span>{graph?.nodes?.length||0} nodes</span><span>{graph?.edges?.length||0} edges</span></div></section><aside className="panel graph-inspector"><div className="panel-heading"><div><span className="kicker">RELATIONSHIP INSPECTOR</span><h2>Operational context</h2></div></div>{detail&&<><div className="selected-device"><span>▱</span><div><b>{detail.device_name}</b><small>{detail.asset_id} · {detail.status}</small></div></div><dl><div><dt>Room</dt><dd>{detail.room}</dd></div><div><dt>Model</dt><dd>{detail.model}</dd></div><div><dt>Lifecycle</dt><dd>{detail.installation_date||"Not recorded"}</dd></div></dl><h3>Direct relationships</h3><div className="edge-list">{graph?.edges?.map((edge,i)=><div key={i}><span>{edge.source}</span><b>{edge.relation.replaceAll("_"," ")}</b><span>{edge.target}</span></div>)}</div><h3>Replacement history</h3><p className="inspector-note">Historical replacement links appear here when returned in this asset’s graph neighborhood.</p></>}</aside></div>;
}
